#This is provided as a convienience that will rebuild ALL container resources.
version: '2'

services:
  gkldap:
    container_name: gatekeeper_local_ldap
    image: osixia/openldap:1.2.0
    command: --copy-service
    mem_limit: 100m
    ports:
      - "389:389"
    environment:
      LDAP_TLS: "false"
    volumes:
      - ./config/ldap/://container/service/slapd/assets/config/bootstrap/ldif/custom
  smtp:
    container_name: gatekeeper_local_smtp
    image: namshi/smtp:latest
    ports:
      - "25"
    mem_limit: 50m
    environment:
      SMARTHOST_ADDRESS: imailgw.finra.org
      SMARTHOST_PORT: 25
  gkdb:
    container_name: gatekeeper_local_postgres
    image: postgres:9.5
    restart: always
    mem_limit: 50m
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: gatekeeper
      POSTGRES_USER: gatekeeper_app
      POSTGRES_PASSWORD: l0ca1t3st

  gkaccounts:
    build:
      context: ./demo-services/fake-account-service
      args:
        jar_file: fake-account-service-*.jar
    mem_limit: 500m
    ports:
      - "8080:8080"
    volumes:
      - ./config/accounts-service/application.yml:/usr/share/gatekeeper/config/application.yml
  gatekeeper-ec2-service:
    depends_on:
      - gkdb
    build:
      context: ./services/ec2
      args:
        jar_file: gatekeeper-ec2-service-*.jar
    mem_limit: 550m
    ports:
      - "8080"
    env_file:
      - config/gatekeeper_config.env
      - config/ec2_service_config.env
    image: gatekeeper/ec2-service:latest
    volumes:
      - ${AWS_DIRECTORY}:/root/.aws
    links:
      - "gkdb"
      - "smtp"
      - "gkldap"
      - "gkaccounts"
  gatekeeper-rds-service:
    depends_on:
      - gkdb
    build:
      context: ./services/rds
      args:
        jar_file: gatekeeper-rds-service-*.jar
    mem_limit: 550m
    ports:
      - "8080"
    env_file:
      - config/gatekeeper_config.env
      - config/rds_service_config.env
    environment:
      - gatekeeper.rds.password=${GATEKEEPER_RDS_USER_PASSWORD}
    image: gatekeeper/rds-service:latest
    volumes:
      - ${AWS_DIRECTORY}:/root/.aws
    links:
      - "gkdb"
      - "smtp"
      - "gkldap"
      - "gkaccounts"
  gatekeeper-ui:
    build:
      context: ./ui
    mem_limit: 50m
    ports:
      - "443"
    links:
      - "gatekeeper-ec2-service"
      - "gatekeeper-rds-service"
  gatekeeper-dev:
    image: gatekeeper/local-proxy
    mem_limit: 50m
    environment:
      - USER=anderj
    ports:
      - "443:443"
    links:
      - "gatekeeper-ui"
  gatekeeper-support:
    image: gatekeeper/local-proxy
    mem_limit: 50m
    environment:
      - USER=bryand
    ports:
      - "444:443"
    links:
      - "gatekeeper-ui"
  gatekeeper-approver:
    image: gatekeeper/local-proxy
    mem_limit: 50m
    environment:
      - USER=wellsh
    ports:
      - "445:443"
    links:
      - "gatekeeper-ui"
